### PR TITLE
Add table indexes to improve read performance

### PR DESCRIPTION
**Pull request by webrgp**
This is a small performance improvement to speed up [reading](https://github.com/internetztube/craft-element-relations/blob/75a6101214fd40e146ddfa22d85b786dc8c0809d/src/services/RelationsService.php#L24-L35) and [deleting](https://github.com/internetztube/craft-element-relations/blob/75a6101214fd40e146ddfa22d85b786dc8c0809d/src/services/ExtractorService.php#L70-L73) query operations, to improve performance.

### CODE REVIEW

**Comment by internetztube** [comment]
Thank you very much!

**Comment by internetztube** [comment]
Thank you! Just released 3.0.7.

**Comment by webrgp** [comment]
@internetztube Thanks for the quick merge, but I am getting errors when updating on composer. Maybe need to update on [packagist](https://packagist.org/packages/internetztube/craft-element-relations)?

**Comment by elivz** [comment]
Hi @internetztube, just chiming in here. I am @webrgp's coworker and we are hoping to roll out this fix to our project this week if possible. Any chance of getting that version updated on packagist? Thanks!

**Pull request merged**
