### PR TITLE
Adds Caching Layer and Console Comands

### LINKED ISSUE #3: Plugin seems to slow down the assets pages
We've noticed searches and asset list pages seem a lot slower now that we've got the plugin running. We've got probably over a thousand images in a bunch of folders. Does your plugin cache the data once it looks up the relations? I know caching is one of the big issues in programming, but wonder if it could be stored until the asset is selected, viewed, edited? Just an idea

### PR DESCRIPTION
**Pull request by gbowne-quickbase**
Boy howdy was this fun! Lots of learning and looking how other plugin greats do things.

- Creates table on install or upgrade.
- Adds command line/console commands to build or refresh the cache
- Builds config/settings model to allow users to define cache duration
- Dramatically speeds up the process for sites with lots of assets and content

Should fix #3

### CODE REVIEW

**Comment by internetztube** [comment]
Wow, thanks for the pull request! Looks great at first glance! Will look closely with the PR the next few days!

**Comment by internetztube** [comment]
Hey Greg! @gbowne-quickbase 
The last few days I made a few adjustments based on your changes.
* Moved Console Commands into Queue Jobs.
* Adapted gathering of Elements with `Element Relations` Fields.
* Created Dedicated Cache Service.
* Code Reformatting

I appreciate your thoroughness regarding docblocks. However, I think that comments are not necessary everywhere.
Of course, type hints are essential for class properties. But if all parameters of a function have a type, a return type, and a meaningful name, then in my eyes, a docblock is not absolutely necessary.  

Please test the code changes again to see if everything works as expected. Thanks, again! 

https://github.com/internetztube/craft-element-relations/tree/next
https://github.com/internetztube/craft-element-relations/compare/858d4e59150f07d7bd1a1f2e460a73c3f2121435...next

**Comment by gbowne-quickbase** [comment]
Great! I'll give it a thorough test. The Queue jobs was a logical next step but I had to get back to my day job!
My IDE encourages doc blocks and for me during development, I found them helpful to make sure I had things named correctly and semantically and to remind me to double check when things got renamed.

**Comment by gbowne-quickbase** [comment]
This seems to be working really well, and I appreciate the use of the Queue, since it's a long process. The only thing I miss is the `create` queue action which would find all the relevant items and build them out to speed up the initial load

**Comment by internetztube** [comment]
I have changed the logic so that there is only one cache refresh endpoint.
Without `--force`, the missing and stale elements are recached.
All elements with an `Element Relations` field are recached with `--force`.

```
php craft element-relations/refresh-cache --force
```

**Comment by gbowne-quickbase** [comment]
That's a great way to do it! Thanks for all your rapid-cycle improvements on this. I hope it's been fun to work on again

**Pull request merged**
